### PR TITLE
Add kitty support to shape

### LINKED ISSUE #5: Add Kitty image protocol support
I might try to contribute this some day. Kitty here refers to kovidgoyal/kitty

### PR DESCRIPTION
**Pull request by ctrlcctrlv**
Close #5

image

### CODE REVIEW

**Comment by simoncozens** [comment]
I'd prefer to keep this as one utility, to make distribution and installation easier; especially since most users will only use one. And there's a lot of repeated code. Why not do a `$ENV` test in Perl?

**Comment by ctrlcctrlv** [comment]
OK; force-pushed. The reason I didn't do it in Perl is so I could avoid having to Google "if-else in Perl", "environment variables in Perl", "string length in Perl", &c. Clearly, you're not amused by my lack of Perl knowledge, so now I'm at least a Perl n00b. 

:-)

By the way, a cool `kitty` feature is that this works in `vim`'s command buffer:

image

**Comment by ctrlcctrlv** [comment]
🦗

**Comment by simoncozens** [comment]
Sorry about the delay - looks good to me!

**Pull request merged**
